// Create Web Server
// npm init
// npm install express --save
// npm install body-parser --save
// npm install multer --save
// npm install mysql --save
// npm install cors --save
// npm install express-session --save
// npm install ejs --save
// npm install nodemon --save-dev
// npm install bcrypt --save
// npm install passport --save
// npm install passport-local --save
// npm install passport-local-mysql --save
// npm install express-mysql-session --save
// npm install connect-flash --save
// npm install express-validator --save
// npm install moment --save
// npm install socket.io --save
// npm install socket.io-client --save
// npm install jquery --save
// npm install bootstrap --save
// npm install popper.js --save
// npm install axios --save
// npm install dotenv --save
// npm install nodemailer --save
// npm install nodemailer-smtp-transport --save
// npm install multer-s3 --save
// npm install aws-sdk --save
// npm install cookie-parser --save
// npm install express-session --save
// npm install express-session --save
// npm install multer-s3 --save
// npm install aws-sdk --save
// npm install cookie-parser --save
// npm install express-session --save
// npm install express-session --save
// npm install multer-s3 --save
// npm install aws-sdk --save
// npm install cookie-parser --save
// npm install express-session --save
// npm install express-session --save
// npm install multer-s3 --save
// npm install aws-sdk --save
// npm install cookie-parser --save
// npm install express-session --save
// npm install express-session --save
// npm install multer-s3 --save
// npm install aws-sdk --save
// npm install cookie-parser --save
// npm install express-session --save
// npm install express-session --save
// npm install multer-s3 --save
// npm install aws-sdk --save
// npm install cookie-parser --save
// npm install express-session --save
// npm install express-session --save
// npm install multer-s3 --save
// npm install aws-sdk --save
// npm install cookie-parser --save
// npm install express-session --save
// npm install express-session --save
// npm install multer-s3 --save
